### ISSUE TITLE
Semantic versioning - 1.0.* gulp-csso to 1.3.* csso

### ISSUE THREAD

**Issue by impatient** [ben-eb/gulp-csso#13]
Wouldn't it make sense to do point releases when updating to point releases of CSSO?

I wouldn't expect 1.0.0 to 1.0.1 to jump the CSSO version to 1.4.  We're seeing some differences between the two and had to peg gulp-csso to 1.0.0.

Thanks for keeping an eye on the project.

**Comment by ben-eb** [comment]
I thought I was following semver; there's no breaking API changes, nor features added in this module, only a dependency bump for CSSO which this module wraps.

Likelihood is that yeah there will be differences in the output as a lot of [bugs have been resolved](https://github.com/css/csso/releases). If there's any specific issues with the output it would be best to report them on the CSSO tracker.
