### ISSUE TITLE
sourcemap support

### ISSUE THREAD

**Issue by paulirish** [ben-eb/gulp-csso#18]
Using this unfortunately breaks my sourcemap pipeline. 

Are you thinking of adding support for gulp-sourcemaps?  It'd be most excellent.

**Comment by paulirish** [comment]
Ah, looks like CSSO doesn't support sourcemaps.  That'll explain why. :)

**Comment by ben-eb** [comment]
Indeed. :smile:

https://github.com/css/csso/issues/173

**Comment by ben-eb** [comment]
Oh, we have this issue also. Still waiting on csso to support sourcemaps first. :smile:

https://github.com/ben-eb/gulp-csso/issues/4

**Comment by lahmatiy** [comment]
@paulirish PR #19
