### ISSUE TITLE
Update CSSO version to ^1.6.0

### ISSUE THREAD

**Issue by corsairdnb** [ben-eb/gulp-csso#20]
Please update `csso` dependency for `gulp-csso`.
CSSO release notes: https://github.com/css/csso/releases/tag/v1.6.0

**Comment by ben-eb** [comment]
Going to save repeating myself here.

https://github.com/ben-eb/gulp-csso/issues/17#issuecomment-183069658

**Comment by corsairdnb** [comment]
Sorry, this was too hard to read package.json :)
