### ISSUE TITLE
Add posibility to pass csso-options

### ISSUE THREAD

**Issue by klausbayrhammer** [ben-eb/gulp-csso#22]
It would be cool if you could pass csso's options (like  debug: true  ) to gulp-csso.

probably like
```js
.pipe(csso({debug:true}))
```

**Comment by lahmatiy** [comment]
PR #19 should make it possible

**Comment by ben-eb** [comment]
Released in `1.1.0`.

https://github.com/ben-eb/gulp-csso#api

**Comment by lahmatiy** [comment]
@ben-eb I think that's should be mentioned in readme also

**Comment by ben-eb** [comment]
What should be mentioned?

**Comment by lahmatiy** [comment]
That plugin options are pass to `csso` as is, but except some settings: `sourceMap` (because of additional logic) and `filename` (`minify()` accepts it, but plugin ignores it in `options`, since it takes from `file`)

**Comment by ben-eb** [comment]
Ahh okay, PR welcome. :smiley:
