### ISSUE TITLE
minified css has been changed

### ISSUE THREAD

**Issue by iamlaobie** [ben-eb/gulp-csso#23]
# origin css:
.page_fea h3:before,
.page_fea h3:after{position: absolute;
                   content:'';
                   background: url(../img/bg.png) 50rem 200rem;
                   background-size:50rem 200rem;
                   background-position:0 -190.2rem;
                   width:2.9rem;
                   height:2.4rem;
                   top:0;}
.page_fea h3:before{left:0;}
.page_fea h3:after{background-position:0 -193.1rem;
                   right:0;
                   top:0.2rem;}

# minified in chrome:
.page_fea h3:before {
    background-position: 0 -190.2rem
}

.page_fea h3:after,.page_fea h3:before {
    position: absolute;
    content: '';
    background: url(../img/bg-fp-e8574ec4.png) 50rem 200rem;
    background-size: 50rem 200rem;
    width: 2.9rem;
    height: 2.4rem;
    top: 0
}

.page_fea h3:before {
    left: 0
}

.page_fea h3:after {
    background-position: 0 -193.1rem;
    right: 0;
    top: .2rem
}

it's really change the css effiective!

**Comment by lahmatiy** [comment]
@iamlaobie Problem is not about plugin but csso. Submit issue here https://github.com/css/csso/issues
Looks like problem is similar to https://github.com/css/csso/issues/143
