### ISSUE TITLE
Publish new version on npm

### ISSUE THREAD

**Issue by lahmatiy** [ben-eb/gulp-csso#26]
@ben-eb Please, publish a new version with CSSO 3.0. I've done with all changes, just `npm publish` left

**Comment by ben-eb** [comment]
Cool! 👍 

Can you revert the version bump? I use https://github.com/sindresorhus/np which does this automatically. 😄

**Comment by lahmatiy** [comment]
@ben-eb Done

**Comment by ben-eb** [comment]
Published. 👍

**Comment by lahmatiy** [comment]
Thank you!
