### ISSUE TITLE
please update to latest CSSO

### ISSUE THREAD

**Issue by yairEO** [ben-eb/gulp-csso#28]
gulp-csso:

    "csso": "^3.0.0"

but current `CSSO` version is `3.1.1`

**Comment by lahmatiy** [comment]
@yairEO That's ok. `^3.0.0` allows patch and minor updates for versions `3.0.0` and above, which includes `3.1.1`. See [The semantic versioner for npm](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) for details

**Comment by yairEO** [comment]
How does that work? what do I need to do in order to have my CSSO module updated?

**Comment by lahmatiy** [comment]
`npm update csso` or `npm update` in your project folder should help. See [npm update](https://docs.npmjs.com/cli/update) documentation for details.

**Comment by yairEO** [comment]
That was of course the first thing I've tried and. both. 
I've verified if it worked by going to:

    \node_modules\csso\package.json

and check the version, which stayed the same `3.0.0`

I had to specifically install `csso` using `npm install csso`

**Comment by lahmatiy** [comment]
I have a couple of assumptions here: an another package pins CSSO version or something wrong with npm client.
If you try to install `gulp-csso` from scratch npm installs `3.1.1`:

```
> npm i gulp-csso
+ gulp-csso@3.0.0
added 60 packages in 6.664s

> cat node_modules/csso/package.json
{
  "_from": "csso@^3.0.0",
  "_id": "csso@3.1.1",
...
  "version": "3.1.1"
}
```
