### ISSUE TITLE
Remove deprecated dependency gulp-util

### ISSUE THREAD

**Issue by stevelacy** [ben-eb/gulp-csso#30]
With the upcoming release of gulp4, gulp-util is deprecated. It should be replaced by dependencies on the individual components used by gulp-csso. The README lists alternatives for the different components. https://github.com/gulpjs/gulp-util

See https://github.com/gulpjs/gulp-util/issues/143

**Comment by lahmatiy** [comment]
Fixed by [3.0.1](https://github.com/ben-eb/gulp-csso/releases/tag/v3.0.1)
