### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by lahmatiy** [ben-eb/gulp-csso#32]
@ben-eb Please, publish a new version on npm, that resolves #30. Everything is ready to publish, just update a version in `package.json` (I think it should be a `3.0.1`, that version I used in the changelog).

**Comment by ben-eb** [comment]
@lahmatiy Can you do it please? I've given you owner on npm. 😄

**Comment by lahmatiy** [comment]
Sure! Thanks a lot! Will do it a bit latter.
