### ISSUE TITLE
please update to latest CSSO

### ISSUE THREAD

**Issue by xdevelx** [ben-eb/gulp-csso#34]
gulp-csso:

`"csso": "^3.0.0"`

but current `CSSO` version is `4.0.2` ([https://github.com/css/csso/blob/master/package.json](https://github.com/css/csso/blob/master/package.json))

**Comment by lahmatiy** [comment]
Done: gulp-csso [4.0.0](https://github.com/ben-eb/gulp-csso/releases/tag/v4.0.0)
